version: '3.1'
services:
  mongo:
    image: mongo
    userns_mode: "host"
    ports:
      - 27017:27017
    volumes:
      - ./dev/instances/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bigbrain